# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- commercial-test

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Debug'

steps:
- script: dotnet nuget disable source "local"
  displayName: 'Disable local packages feed' 

- script: dotnet restore --configuration $(buildConfiguration) FakeXrmEasy.Samples.sln
  displayName: 'dotnet restore $(buildConfiguration)'

- script: dotnet build --configuration $(buildConfiguration) FakeXrmEasy.Samples.sln
  displayName: 'dotnet build $(buildConfiguration)'
